### ISSUE TITLE
Clean up `DatasetMetadata` / `DatasetFactory` meta-issue

### ISSUE THREAD

**Issue by lr4d** [JDASoftwareGroup/kartothek#321]
`DatasetMetadata` / `DatasetFactory` refactoring:
- [ ] https://github.com/JDASoftwareGroup/kartothek/issues/320
- [ ] https://github.com/JDASoftwareGroup/kartothek/issues/311
- [ ] https://github.com/JDASoftwareGroup/kartothek/issues/282, specifically also https://github.com/JDASoftwareGroup/kartothek/issues/282#issuecomment-631278716

On `delete_scope` / `DatasetMetadataBase.query` (all very related):
- [ ] https://github.com/JDASoftwareGroup/kartothek/issues/196
- [ ] https://github.com/JDASoftwareGroup/kartothek/issues/202
- [ ] https://github.com/JDASoftwareGroup/kartothek/issues/198
